name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable
      - uses: actions/upload-artifact@v4
        with:
          name: livraisons-apk
          path: ${{ steps.buildozer.outputs.filename }}
